//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Serializable()]
public class AwardData
{
    
    public int id;
    
    public int Grade;
    
    public string CompanyName;
    
    public string AwardName;
    
    public int Price;
    
    public string ImagePath;
}
