//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Serializable()]
public class PlayerData
{
    
    public float posX;
    
    public float posY;
    
    public float posZ;
    
    public float rotX;
    
    public float rotY;
    
    public float rotZ;
    
    public float oxygen;
    
    public float weight;
}
