//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Serializable()]
public class StatData
{
    
    public int id;
    
    public string Name;
    
    public int Level;
    
    public int Hp;
    
    public int Exp;
    
    public int Str;
    
    public int Dex;
    
    public int Con;
    
    public int Int;
}
